ONYX_TENSILE_STRENGTH_MPA: float = 36.0
ONYX_ELASTIC_MODULUS_GPA: float = 2.4
ONYX_FATIGUE_EXPONENT: float = 10.0
ONYX_ENERGY_ABSORPTION_COEFFICIENT: float = 0.7
ONYX_DENSITY_KG_M3: float = 1180.0
DEGRADATION_PER_CYCLE_BASE: float = 0.0001
MAX_DEGRADATION: float = 1.0
